### ISSUE TITLE
contribution guidelines and FAQ

### ISSUE THREAD

**Issue by anarcat** [linkcheck/linkchecker#1]
i think the first step here is to document this fork and why it's there. lots of details are in https://github.com/wummel/linkchecker/issues/686, but it should be summarized in the documentation.

we should also formalize how we want to collaborate.

so - shopping list:

* [ ] document the fork and its reasons (summarize https://github.com/wummel/linkchecker/issues/686)
* [ ] document branches and protection - some of that done in #32, but needs details about specific branch support status
* [ ] add issue templates
* [x] document contribution guidelines - see #32
* [ ] adopt a code of conduct - see #32, not adopted yet
* [ ] add support section? FAQ, troubleshooting, proper bug reporting and so on... maybe based on [monkeysign's support section](http://monkeysign.readthedocs.io/en/2.x/support.html)?

**Comment by anarcat** [comment]
FWIW, i enabled branch protection on the project. here are the restrictions:

## `master`

* *Require pull request reviews before merging*
* *Require status checks to pass before merging* (travis must be green!) and *Require branches to be up to date before merging*

## `9.3.x`, the "stable" branch

same as `master`, plus only admins can push (ie. just me for now, i'm happy to grant this to others who are interested).

**Comment by anarcat** [comment]
okay, so the permissions were wrong on the organization - members only had read permission. we found out in #19 that @mgedmin couldn't merge his own PR even though I had approved it.

i switched the default permission to "write" which should fix this. @mgedmin can you confirm this is fixed when the next PR comes in?

I haven't made the default permission `admin` just yet. right now i am still the gatekeeper of who's in and out, and i'd like to keep that while we formalize this process.

but hopefully every member should be able to merge code now.

**Comment by anarcat** [comment]
@mgedmin by the way, next time something happens, do say something. :) it is not my intention to monopolize control over this project, far from it! so if you need something, just ask, and i'll give it.

**Comment by anarcat** [comment]
#22 shows we should have issue templates as well. :)

**Comment by anarcat** [comment]
i started working on this. i added a bullet list in the issue summary - and i noticed we maybe should have a more general support section than just a FAQ...

**Comment by anarcat** [comment]
alright - the goods are in #32, please review and comment!

**Comment by anarcat** [comment]
this is not done! we only have a few bullets done in #32, but not all...

**Comment by pmac** [comment]
If a full org turns out to be too much this project could potentially be a good candidate for moving to the [Jazzband](https://jazzband.co/).
