### ISSUE TITLE
namespace issues [meta]

### ISSUE THREAD

**Issue by anarcat** [linkcheck/linkchecker#136]
we have a bunch of issues regarding the naming of this project.

 - [ ] access to the linkchecker repo on PyPI (#4)
 - [ ] access to the linkchecker repo on GitHub (https://github.com/linkchecker/linkchecker.github.io/issues/2)
 - [ ] wummel.github.io still present in error messages (#110) and source code
 - [ ] we have two orgas on Docker (#135)
 - [ ] new website links to old website (#112)
 - [x] tests were failing on old infra (#7)
 - [ ] the command name is `linkchecker`
 - [x] the module name is `linkcheck`

I figured I would create a meta-issue to regroup those, so that we keep track of this mess.

It seems more and more obvious that it will be impossible to reclaim the `linkchecker` namespace everywhere, so it looks like we'll have to fallback to `linkcheck` or `linkchecker2`. considering we have the former namespace on GH, i'd be tempted to switch to that.

opinions? alternatives? despair? ;)

**Comment by ThomDietrich** [comment]
Intuitively I'd expect `linkcheck` to be inferior. Even though that is just an uneducated hunch, I feel many will get trapped on that thought.
I'd suggest something like `linkchecker2` or an extended name like `linkchecker-reborn`

**Comment by anarcat** [comment]
inferior? why? could you expand?

the problem with `linkchecker2` is that we're at version 9 now. :p i don't like `-reborn`, `-ng` is more traditionnal, but it's not really the effort we're on now... we're not rebuilding this or doing a "new generation", we're just keeping the project alive...

**Comment by ThomDietrich** [comment]
Maybe it's just me 😄 My thought might have been a bit shortsighted.
I have to agree, `-reborn` is not my brightest idea and your argument against such an addition also makes a lot of sense.

Looking at the issue a second time I can't find a good reason why the simple `linkcheck` would not be an option.

**Comment by mgedmin** [comment]
I prefer linkchecker2.  It's the Python convention (e.g. urllib -> urllib2 -> urllib3), and it explicitly acknowledges the project ancestry (yes, linkchecker2 is related to the older linkchecker).

I don't think version numbers are important (urlib3 is currently at version 1.22).

(linkcheck is fine for the GitHub organisation name IMHO.)

**Comment by anarcat** [comment]
understood. for the record, there's some progress in the PyPI front (#4 ) as the PEP to formalize this process was approved. to reclaim the linkchecker name, the next step would be to address github to retake the `linkchecker` organisation (https://github.com/linkchecker/linkchecker.github.io/issues/2)

**Comment by anarcat** [comment]
so i don't mind much between linkcheck and linkchecker. you're right that the "2" suffix is more customary in python, even if I've always found that strange myself.

but that seems to me to be a major undertaking: we need to rename a bunch of stuff, don't we? I'm not even exactly sure where to begin with that, but there's at least stuff in `setup.py` that needs to change...

where else do we need to rename things?

in the meantime, i'll just go ahead and tag a 9.4.0 release to ship the nice stuff we've built on the master branch in the last year or so. it's kind of ridiculous to be blocking on all this administrative stuff while other things (e.g. the debian package, which is still stuck) can still move forward even though some parts are blocked.

**Comment by anarcat** [comment]
as a stopgap measure, 9.4.0 was released, see #141 for details.

**Comment by anarcat** [comment]
i've opened #143 and #144 to remove traces of wummel on the website at least. i figured i would also remove the build links from there, but I realized in doing those PR that I don't actually understand the website workflow... right now I edit the raw HTML and the source at once, how am i supposed to update the branch from the source?

**Comment by mgedmin** [comment]
> right now I edit the raw HTML and the source at once, how am i supposed to update the branch from the source?

I think we'll have to invent a workflow.

We could be using ReadTheDocs -- I use that for [objgraph](https://github.com/mgedmin/objgraph/); ReadTheDocs basically watches for commits and git tags in the github repo and builds Sphinx docs in `docs/` at the repository root.

We could be using GitHub pages -- I used that before once, a long time ago.  It exports the gh-pages branch (as static HTML or as a Jekyll site; but I'm not familiar with Jekyll so I never used that).  We'd have to come up with a workflow to generate the static HTML files in the gh-pages branch: a Travis CI job that gets an (encrypted) github access token so it can watch for commits to docs/ on master, run the build, import the generated files into a git commit on the gh-pages branch and push that back to GitHub seems to be a common solution, although I've not used it before.  Or it might be overkill, we could do a manual 'make publish-docs' that builds the things runs ghp-import to update the gh-pages branch, then git push to publish the updated website.

We could be using both (one for documentation, one as a front page with download links and whatnot).

ReadTheDocs seems like a simpler solution.

**Comment by anarcat** [comment]
would you mind if we moved that conversation to #142 ? :)

**Comment by mgedmin** [comment]
I thought #142 covered only half of the conversation topic ;)

But sure, let's not hijack the meta task for this one detail.

**Comment by anarcat** [comment]
GitHub's response regarding the `linkchecker` orga is that "usernames are assigned on a first-come, first-serve basis" and the name is "not available". If we own the trademark (!) we can make a claim according to their [trademark policy](https://help.github.com/articles/github-trademark-policy/) so I guess that would be the next step (ie. learn trademark law?!).

**Comment by anarcat** [comment]
i've created the [meta] tag to track those issues that are piling up.

**Comment by anarcat** [comment]
progress in linkchecker/linkchecker.github.io#2: i am now owner of the repo! we just need to figure out what to do with the current owner and remaining repos. but progress! yay!

**Comment by anarcat** [comment]
the previous owner removed himself from the organization, and i have invited everyone here to join, whoohoo! next step is to migrate the repos from here to there, and we'll have the github par solved at last.

**Comment by anarcat** [comment]
after migrating all the repos in the old linkcheck organization, i've checked the github box: I don't think there's anything left here.

the only real blocker left is still PyPI (#4).

**Comment by ThomDietrich** [comment]
Great progress @anarcat Kudos and congrats!!

**Comment by cjmayo** [comment]
Checked off the wummel.github.io task (didn't realise these changed without confirmation...). We fixed the last of these, #110 (which I have closed) in 004632a by #242.
